---
- hosts: local
  tasks:
    - name: Generate configuration file
      template: src=./access_switch.j2 dest=./{{item.hostname}}.txt
      with_items:
        - {hostname: sw1, ip_addr: 10.1.0.100, default_gateway: 10.1.0.1, secret: donttell, access_vlan: 10, snmp_community: yow}
        - {hostname: sw2, ip_addr: 10.2.0.100, default_gateway: 10.2.0.1, secret: donttell, access_vlan: 20, snmp_community: yow}
        - {hostname: sw3, ip_addr: 10.3.0.100, default_gateway: 10.3.0.1, secret: donttell, access_vlan: 30, snmp_community: yow}
        - {hostname: sw4, ip_addr: 10.4.0.100, default_gateway: 10.4.0.1, secret: donttell, access_vlan: 40, snmp_community: yow}
        - {hostname: sw5, ip_addr: 10.5.0.100, default_gateway: 10.5.0.1, secret: donttell, access_vlan: 50, snmp_community: yow}
